name: Deploy VNet Bicep file
on:
  workflow_dispatch
jobs:
  vnet-build-and-deploy:
    environment: Shared Platform
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: NetworkRG
        template: ./coreplatform/vnet.bicep
        parameters: ./coreplatform/vnet.parameters.bicep
        failOnStdErr: false
